# Generated by Django 5.0.4 on 2024-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='frecuenciaDeCompra',
            field=models.IntegerField(default=0),
        ),
    ]
