# Generated by Django 5.0.4 on 2024-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_frecuenciadecompra_producto_cadacuantosdias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuarioAsignado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
