# Generated by Django 5.0.4 on 2024-05-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_producto_usuarioasignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ultimoPedido',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
