# Generated by Django 5.0.6 on 2024-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_historialpedidos_notificado_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='mostrado',
            field=models.BooleanField(default=False),
        ),
    ]
