# Generated by Django 5.0.6 on 2024-05-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_notificaciones_mostrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='estadoPedido',
            field=models.CharField(default='Rechazado', max_length=50),
        ),
    ]
